sudo: false
dist: trusty
language: php
matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - dist: precise
      php: 5.3
before_script:
  - composer install