name: Syntax check

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-16.04, ubuntu-latest]
        php-version: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
    - name: Syntax check
      run: |
        find -L . -path ./vendor -prune -o -path ./tests -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
      env:
        CI: true
